# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: tip_calc_development
  pool: 5
  username: tip_calc
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: tip_calc_test
  pool: 5
  username: tip_calc
  password: password1

production:
  adapter: postgresql
  encoding: unicode
  database: tip_calc_prod
  pool: 5
  username: tip_calc
  password: password1
